#!/bin/sh

# Copyright 2021 Balena Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Migrate current state in apps.json from v2 to v3 target state
#

set -e

#
# MAIN
#

DATA_MOUNT="/mnt/data"
APPS_JSON_NAME="apps.json"
APPS_JSON_PATH="${DATA_MOUNT}/${APPS_JSON_NAME}"

if [ -f "${APPS_JSON_PATH}.v2" ]; then
	# Even if they are equal we would need to write to delete v2
	# so no need to compare checksums, just overwrite it
	mv "${APPS_JSON_PATH}.v2" "${APPS_JSON_PATH}"
	sync
	echo "[INFO] 76-fwd_cleanup_current-state: Migration failed - restored saved v2 current state."
else
	if [ ! -f "${APPS_JSON_PATH}" ]; then
		echo "{}" > "${APPS_JSON_PATH}"
		sync
		echo "[ERROR] 76-fwd_cleanup_current-state: No current state, setting empty."
	fi
fi
